# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 10:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_remove_todo_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 29, 10, 41, 20, 355522, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
