# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 10:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_todo_created'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
